server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowModelTypeConfiguration.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowServerRuntimeModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/di/GLSPModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/model/ModelTypeConfiguration.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ModelOptions.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SaveModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/FileBasedModelFactory.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/ModelStateImpl.java

Refactors  and extracts common functionality from the filebased Modelfactory.  We have now three independent components which are  responsible for loading,saving and model configuration.
In addition, the filebased Modelfactory is now completely generic and  injected by default.
This also solves the issue with the @singleton annotation mentioned in #61

Refactor Filebased Modelfactory #64

---

client/packages/glsp-theia-extension/src/browser/diagram/glsp-diagram-manager.ts
client/packages/glsp-theia-extension/src/browser/frontend-extension.ts

This is a preparation PR for #20. 
Extracts the (re)-binding of the OperationService to the SprottyDI container from the theia-glsp submodule. 
This is glsp-specific code (i.e. palette specific) and should not be in the general theia-sprotty glue code repository
Our contributions to the glue code repository for now are :
* Extraction of a generic TheiaSprottyConnector
* Adaption of the existing TheiaSprottyConnector to conform to this interface (and renaming to LSPTheiaSprottyConnector)
* Implementation of TheiaSelectionConnector

Extract OperationService binding  from theia-glsp

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/AbstractActionHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionRegistry.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/di/GLSPModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/model/ModelStateProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/DefaultGraphicalLanguageServer.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/CollapseExpandActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ComputedBoundsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OpenActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestOperationsHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestPopupModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SaveModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SelectActionHandler.java

This PR enables the handling of multiple clients/diagram with one instance of DefaultGraphicalLanguageServer.
For each connected client the server maintains an own model state. The  state object is chosen via clientId of the actionMessage and then delegated to the corresponding action handler. 
This partly fixes #39. Selecting a tool from the palette doesn't work reliably with multiple clients (probably related to the Operation Service handling). But since this is a client side problem I will open a  separate issue once this is merged. 
In addition, reopening a diagram doesn't work yet but I opened #76 for that.

Implement server side handling of multiple clients/diagrams #39

---

.travis.yml

In addition the build pushed branches settings on the travis ci configuration as been set to true.
Travis should now trigger a build for each PR and for each change merged to master. (The build triggered on master can then serve as entrypoint for nightly/next release of the npm and maven packages)

Update travis.yml to trigger build when changes are pushed to master

---

.travis.yml
client/package.json
scripts/deployMaven.sh
scripts/deployNPM.sh
server/settings.xml

Updates Travis configuration and adds deployment steps:
* Successful builds on master that affect npm code (i.e. file changes in client directory) will trigger deployment of the glsp npm packages with the "next" tag (i.e. snapshot release)
* Successful builds on master that affect java code (i.e file changes in the server directors) will trigger
deployment of the maven modules to sonatype snapshot repository)

Add travis deployment configuration

---

client/examples/workspace/example1.wf
client/packages/glsp-sprotty/src/features/execute/di.config.ts
client/packages/glsp-sprotty/src/features/execute/execute-command.ts
client/packages/glsp-sprotty/src/features/execute/model.ts
client/packages/glsp-sprotty/src/index.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts
client/packages/workflow-sprotty/src/di.config.ts
client/packages/workflow-sprotty/src/model.ts
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowServerRuntimeModule.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/SimulateCommandHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/schema/Icon.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ExecuteServerCommandAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/handler/ServerCommandHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/model/ModelState.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/HandlerProvider.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ModelOptions.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/OptionsUtil.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ExecuteServerCommandActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/provider/DefaultActionProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/provider/DefaultServerCommandHandlerProvider.java

This PR adds a sprotty feature extension which enables sprotty elements to act as command executor.
A commandExecutor has a command Id property. On double-click the commandExecutor sends a ExecuteServerCommandAction to the server.
* Implementation of the 'CommandExecutor" sprotty feature.
* Implementation and registration of the ExecuteServerCommand action on client/server side

Feature for executing commands on server side

---

client/packages/glsp-sprotty/package.json
client/packages/glsp-sprotty/src/features/tools/delete-tool.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts
client/yarn.lock
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ActionKind.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/DeleteElementOperationAction.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/operationhandler/DeleteHandler.java

This changes rebases our implementation on the current sprotty version ("next") (as mentioned in #20)
Sprotty has  also introduced a <b> DeleteElementAction </b> which is now in conflict with the <b>DeleteElementAction</b> of GLSP. As a consequence I removed our Action definition and reused the action provided by sprotty. 
When working on issue #92 we should also check if there are other sprotty actions which we can reuse.

 Rebase glsp on sprotty "next"

---

scripts/deployNPM.sh
scripts/setVersions.sh

Add a shell script to the deployment process which changes the version numbers of the glsp plugin to "next" before deploying a snapshot npm package

Improve npm deployment

---

client/packages/glsp-sprotty/src/features/tool-manager/tool-manager.ts
client/packages/glsp-sprotty/src/features/tools/key-tool.ts

Modifies the <i>StandardToolsEnablingKeyListener</i> to ensure that the StandardTools get enabled after a CreationTool has been used in "stamp-mode" (i.e. while holding ctrl)
In addition, this contains a minor refactoring for the <i>ExtendedKeyTool</i> which was using (and exporting) an unsafe custom type guard function instead of a simple 'instanceof' check

Fix #105 "stamp" mode not working

---

client/yarn.lock

This PR rebuilds the yarn lock file. The build failed because  we were hard pinned to a transitive dependency which has been removed due to the [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)

Fix current build issues

---

client/packages/glsp-sprotty/src/base/command-stack.ts
client/packages/glsp-sprotty/src/base/di.config.ts
client/packages/glsp-sprotty/src/index.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts
client/packages/workflow-sprotty/src/di.config.ts

This change provides an extension of the sprotty command stack which is observable.
Registered instances of <i>CommandStackObserver</i> get notified if an update command was triggered from the server and can process the model before it's delegated to the viewer.
This should provide the necessary functionality for tools to (re)apply their visual feedback if the server updates the model during tool execution.

Fix #111- Introduce observable command stack

---

client/examples/workspace/example1.wf
client/packages/glsp-theia-extension/src/browser/diagram/glsp-palette-contribution.ts
client/packages/workflow-sprotty/src/di.config.ts
client/packages/workflow-sprotty/src/model-factory.ts
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowModelTypeConfigurationProvider.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowOperationConfiguration.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateAutomatedTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateDecisionNodeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateManualTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateMergeNodeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateWeightedEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/schema/ActivityNode.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/schema/ModelTypes.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/schema/TaskNode.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/schema/WeightedEdge.java

With this change it's always possible to match an operation to its corresponding elementType and vice versa
+ Use actual elementTypeId in operation declaration
+ Create ModelTypes constants class for the workflow example to improve maintainability
+ Refactor modelType IDs for task- & activity-nodes.
+ Ensure that each distinct model element has its own unique elementTypeId 
_Note: The header of newly introduced classes is already updated to conform to #142_

Fix #143 Match operation element type id and actual type id

---

client/packages/glsp-sprotty/src/base/command-stack.ts
client/packages/glsp-sprotty/src/base/di.config.ts
client/packages/glsp-sprotty/src/base/diagram-ui-extension/diagram-ui-extension-registry.ts
client/packages/glsp-sprotty/src/base/model/model-update-observer-registry.ts
client/packages/glsp-sprotty/src/features/hints/di.config.ts
client/packages/glsp-sprotty/src/features/hints/type-hints-action-initializer.ts
client/packages/glsp-sprotty/src/features/tool-feedback/di.config.ts
client/packages/glsp-sprotty/src/features/tool-feedback/feedback-action-dispatcher.ts
client/packages/glsp-sprotty/src/features/tool-palette/di.config.ts
client/packages/glsp-sprotty/src/features/tool-palette/tool-palette.ts
client/packages/glsp-sprotty/src/features/tools/change-bounds-tool.ts
client/packages/glsp-sprotty/src/index.ts
client/packages/glsp-sprotty/src/types.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts

The initial implementation was sort of a hacky approach that was tinkered into the GLSPCommandStack. In addition, it required a direct dependency between diagram server and commandstack for the sole purpose of setting a boolean flag to true 
I propose another more stable approach replacing the original handlers for Set- and UpdateActions with a custom handler that is observer-aware and delegates the model to each observer before the corresponding command is created.
This PR also contains the following minor changes:
- Introduce a common base class for classes that are both action handler and initializer
- Update GLSP_TYPES to also contain Symbols for non interface-derived types (e.g. DiagramUIExtensionRegistry)

#111 Refactor ModelUpdateObserver implementation

---

client/packages/glsp-sprotty/src/features/tools/creation-tool.ts
client/packages/glsp-sprotty/src/features/tools/drag-aware-mouse-listener.ts

Fix #168 by making the edge creation tool more resilient to mouse dragging operations during the operation.
This change also introduces `DragAwareMouseListener` to make it easier for mouse listeners based tools to react only to mouse up events without prior dragging or with prior dragging.
The node creation tool as well as the edge creation tool now only react to non-dragging mouse up events, so that the user can drag in the diagram without changing the state of the node or edge creation tools. This fixes #167.

Support dragging while node and edge creation (#167, #168)

---

client/packages/glsp-sprotty/css/glsp-sprotty.css
client/packages/glsp-sprotty/src/features/reconnect/model.ts
client/packages/glsp-sprotty/src/features/tool-feedback/change-bounds-tool-feedback.ts
client/packages/glsp-sprotty/src/features/tool-feedback/creation-tool-feedback.ts
client/packages/glsp-sprotty/src/features/tool-feedback/di.config.ts
client/packages/glsp-sprotty/src/features/tool-feedback/reconnect-tool-feedback.ts
client/packages/glsp-sprotty/src/features/tools/default-tools.ts
client/packages/glsp-sprotty/src/features/tools/reconnect-tool.ts

- Provide tool to reconnect source or target of an existing edge
- Implement source selection feedback for reconnection
- Reuse target selection feedback from edge creation tool
- Register reconnect tool as standard tool
- Fix typo in change bounds tool feedback (elementTypeId -> elementId)

Resolve #29: Implement EdgeReconnectTool as standard tool

---

client/examples/workflow/workflow-sprotty/src/di.config.ts
client/examples/workflow/workflow-sprotty/src/workflow-views.tsx
client/packages/glsp-sprotty/src/base/command-stack.ts
client/packages/glsp-sprotty/src/features/command-palette/action-provider.ts
client/packages/glsp-sprotty/src/features/reconnect/model.ts
client/packages/glsp-sprotty/src/features/request-response/di.config.ts
client/packages/glsp-sprotty/src/features/request-response/support.ts
client/packages/glsp-sprotty/src/features/select/selection-tracker.ts
client/packages/glsp-sprotty/src/features/tool-feedback/creation-tool-feedback.ts
client/packages/glsp-sprotty/src/features/tool-feedback/reconnect-tool-feedback.ts
client/packages/glsp-sprotty/src/features/tools/change-bounds-tool.ts
client/packages/glsp-sprotty/src/features/tools/creation-tool.ts
client/packages/glsp-sprotty/src/features/tools/reconnect-tool.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts
client/yarn.lock

- Replace 'Routable' interface with 'SRoutableElement' class
- Provide isRoutable function to replace sprotty one
- Provide createReconnectHandle function (now hidden in LinearEdgeRouter)
- Remove unnecessary button handler registry for SelectionTracker
- Replace usage of ActionHandlerRegistry with IActionHandlerInitializer
- Use AnchorComputerRegistry for edge anchoring
- Update yarn.lock and fix compilation errors

Fix #186: Migrate to new sprotty Routing API

---

README.md

We only gave information about starting the GLSP server from the IDE. But people might want to start the server also just from the command line without setting up an IDE workspace.
This change also adds a link to the EclipseCon talk about GLSP.
Fixes #189

Add information on starting server from cmd line

---

client/packages/glsp-sprotty/src/features/operation/set-operations.ts
client/packages/glsp-sprotty/src/features/reconnect/action-definitions.ts
client/packages/glsp-sprotty/src/features/tools/reconnect-tool.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowServerRuntimeModule.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/ReconnectEdgeHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/Action.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ReconnectConnectionOperationAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/operations/Operation.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/SModelIndex.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/provider/DefaultActionProvider.java

- [server] Provide ReconnectConnectionOperationAction and handler
- [client] Provide ReconnectConnectionOperationAction and use it
The PR for the updated specification can be found under https://github.com/eclipsesource/GraphicalServerProtocol/pull/6.

Resolve #182: Implement Reconnect Connection operation

---

client/packages/glsp-sprotty/src/features/reconnect/model.ts

The selected reconnect handles mess up the selection tracking of the change bounds tool, as they never get properly de-selected through mouse or key events (how the change bounds tool tracks selection). The change bounds tool therefore always thought we had a multi-selection case for which the tool is not "active". This fix therefore ensures that reconnect handles are never selected in the first place.
As a result, the connectable that you click when changing the source or target of an edge, now shows resize handles (as both are default tools and always active).
Please note that in the long run I believe that we will encounter similar issues as the selection tracking is currently very unstable: It only tracks key and mouse events (as this is the level on which the tools operate), so any …

Fix #185: Ensure elements can be resized after using the reconnect tool

---

client/.vscode/extensions.json
client/.vscode/settings.json

I think this will help with the unnecessary conflicts we often have on
the lines with imports. I configured this extension as recommended
ones so that they should be suggested by VSCode on first open.

Automatically split and organize imports with split-n-sort extension

---

client/examples/workflow/workflow-sprotty/src/di.config.ts
client/packages/glsp-sprotty/css/glsp-sprotty.css
client/packages/glsp-sprotty/src/features/operation/set-operations.ts
client/packages/glsp-sprotty/src/features/reconnect/action-definitions.ts
client/packages/glsp-sprotty/src/features/reconnect/model.ts
client/packages/glsp-sprotty/src/features/tool-feedback/di.config.ts
client/packages/glsp-sprotty/src/features/tool-feedback/edge-edit-tool-feedback.ts
client/packages/glsp-sprotty/src/features/tools/change-bounds-tool.ts
client/packages/glsp-sprotty/src/features/tools/default-tools.ts
client/packages/glsp-sprotty/src/features/tools/edge-edit-tool.ts
client/packages/glsp-theia-extension/src/browser/diagram/glsp-theia-diagram-server.ts
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowServerRuntimeModule.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/RerouteEdgeHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/Action.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/RerouteConnectionOperationAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/operations/Operation.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/provider/DefaultActionProvider.java

- [server] Implement RerouteConnectionOperationAction and handler
- [client] Include edge edit and edge layout module from sprotty
- [client] Provide routing handles as feedback (SwitchEditModeAction)
- [client] Rename 'EdgeReconnectTool' to 'EdgeEditTool'
- [client] Send RerouteConnectionOperationAction from edge edit tool
- [client] Remove multi-selection restriction on change-bounds-tool

Resolve #194: Provide re-routing action for edges

---

client/.vscode/extensions.json
client/.vscode/settings.json

The default organize imports action of VS code does not play along with `import split'n'sort`. (see #199)
This change uses the `TypeScript Hero` plugin to organize imports instead. 
Note: Typscript Hero also provides the possibility to sort imports but in my opinion the sorting of `import split'n'sort` is superior. If needed we can rely only on TypeScript Hero as well. The sorting then will look similar to the style used in the JsonForms project.

Fix #199 Use Typscript Hero to organize imports

---

README.md
client/.vscode/launch.json
client/.vscode/tasks.json
client/examples/workflow/browser-app/package.json
client/package.json

Fixes and streamlines the scripts in the package.jsons, tasks.json,
and launch.json. Also adds the usage of those configurations to
the readme.
Fixes #212

Configure and document watching (#212)

---

.travis.yml

Moving the problematic encrypted environmental variables in the before deployment section should fix this issue because we only deploy on the master branch.

Resolve #218- Update travis.yml

---

client/examples/workflow/browser-app/package.json
client/examples/workflow/workflow-glsp-extension/package.json
client/examples/workflow/workflow-sprotty/package.json
client/package.json
client/packages/glsp-sprotty/package.json
client/packages/glsp-theia-extension/package.json
client/tsconfig.json
client/yarn.lock

For our dependencies to sprotty, sprotty-theia and all `@theia` packages, we are currently using the "next" tags. This makes our nightly build extremely unstable and introduces potential version mismatches when our npm packages are consumed.
This PR improves this "dependency hell" by 
- using the latest stable version (0.5.0) instead of next for all `@theia` dependencies. Currently, there is no need to consume the nightly theia build anyways
- pinning the version of sprotty and sprotty-theia to a concrete next version instead of using the tag.
- Using the yarn selective resolution feature to enforce these versions also for the "sprotty-theia" package

Improve stability of dependencies for nightly/next builds

---

server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerLauncher.java

- Add an asyncRun() and stop() method to ServerLauncher
- Change the implementation to avoid the infinite loop
fixes #238
Signed-off-by: Camille Letavernier <cletavernier@eclipsesource.com>

Provide a stoppable implementation of ServerLauncher

---

server/glsp-server/src/main/java/com/eclipsesource/glsp/server/DefaultGLSPServer.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OpenActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java

Some Java classes were importing the wrong `@Inject` annotation which could cause issues when consuming the GLSP packages via maven central.

Fix wrong Inject imports

---

.travis.yml
client/yarn.lock
scripts/deployMaven.sh
scripts/deployNPM.sh
scripts/deployP2.sh
server/pom.xml

- Clean-up of maven build #41
- Fix selective deployment #241
- Add `deployP2.sh` script and integrate in Travis build.
The `deployP2.sh` script is triggered after each successful maven deployment. The script
- regenerates the glsp-p2 repository
-  builds and uploads the repository  to bintray
- commits and tags the changes and pushes to https://github.com/eclipsesource/glsp-p2
(The  deployed repository will be available here https://dl.bintray.com/eclipsesource/glsp/nightly)

Improve CI Build

---

client/examples/workflow/workflow-sprotty/src/di.config.ts
client/packages/sprotty-client/src/features/layout/di.config.ts
client/packages/sprotty-client/src/features/layout/layout-commands.ts
client/packages/sprotty-client/src/features/tools/change-bounds-tool.ts
client/packages/sprotty-client/src/index.ts
client/packages/sprotty-client/src/utils/smodel-util.ts
client/packages/theia-integration/src/browser/diagram/glsp-diagram-commands.ts
client/packages/theia-integration/src/browser/frontend-module.ts

Action and command to resize given or selected elements to:
- min/max/avg/first/last width or height
Action and command to align given or selected elements to:
- left/center/right for all/first/last selected element(s)
- top/middle/bottom for all/first/last selected element(s)
Use keybindings within Sprotty for some actions
Register actions in the 'Diagram' menu for Theia

Fixes #266: Introduce layout commands for sizing and aligning elements

---

server/pom.xml

Reconfigure maven-javadoc-plugin to avoid errors due to incomplete javadoc during deployment process

Fix Travis CI Build

---

server/glsp-graph/src/main/java/com/eclipsesource/glsp/graph/impl/GModelIndexImpl.java

Otherwise the index's methods like findByClass don't work.

ECrossReferenceAdapter doesn't store target so we store it ourselves

---

.travis.yml
server/glsp-graph/src/main/java/com/eclipsesource/glsp/graph/impl/GModelIndexImpl.java

- Iterate on the node's children when indexing a new node
fixes #284
Signed-off-by: Camille Letavernier <cletavernier@eclipsesource.com>

GModelIndexImpl isn't recursive

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionDispatcher.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/di/GLSPModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/jsonrpc/GLSPClientProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/DIActionDispatcher.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/di/DefaultGLSPModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/jsonrpc/DefaultGLSPClientProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/jsonrpc/DefaultGLSPServer.java

- Add a method to ActionDispatcher to send actions to the client directly
- Add a mapping from clientId to GLSPClient in the new GLSPClientProvider API
- I'm not 100% satisfied with this: the client ID is specific to each client, so the same clientID can exist in different instances of GLSPServer. However, all instances of GLSPServer use the same GSLPClientProvider so they currently conflict with each other. We could register a (GLSPServer, clientId) pair instead to avoid this issue. On top of that, the clientID is not initially known to the GLSPServer; it's only known when we receive the first message (Typically OpenModel, I guess), so I'm not sure when/where's the best place to register this ClientID - to - GLSPClient mapping

[297] Add support for server to client updates

---

server/pom.xml

Deactivate the maven-java-doc plugin for now. The JDK11 version used by Travis has a known bug with the maven-java-doc plugin.
This got already fixed in newer JDK releases. Can be reactivated once Travis updates to a new version.

Fix travis build

---

server/glsp-server-websocket/src/main/java/com/eclipsesource/glsp/server/websocket/GLSPConfigurator.java
server/glsp-server-websocket/src/main/java/com/eclipsesource/glsp/server/websocket/WebsocketServerLauncher.java

The P2 counterpart of glsp-server-websocke was not working because javax.websocket relies on some services that should be provided via `ServiceLoader`. This is not always the case when using the plugin in an OSGI context.
This change introduces a `GLSPConfigurator` for ServerEndpoints that has a fallback option if no service is provided via ServiceLoader.
(Integrated and tested locally in the glsp-p2 repository)

Fix #311 Implement GLSPConfigurator for websocket connections

---

server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowFacade.java

This change ensures that `WorkflowFacace.initializeNotation()` reuses diagrams that already exist in the notation resource instead of creating new ones.
If a new diagram is created at runtime it`s also added to the notation resource.
This ensures that the GLSP server also can handle and process empty notation files accordingly

Ensure that notation initialization reuses existing diagrams

---

client/packages/sprotty-client/src/features/tools/creation-tool.ts

The issue was caused by the animation framework accessing the parent of the feedback edge's parent, which didn't exist anymore. Therefore, we now make sure that we remove the feedback edge accordingly after the successful creation of an edge in stamp mode.
Resolves #314

Fix stamp mode for creating connections

---

client/examples/workflow/workflow-modelserver-theia/src/browser/diagram/workflow-diagram-label-provider-contribution.ts
client/examples/workflow/workflow-modelserver-theia/src/browser/frontend-module.ts

This unifies the icons of workflow diagrams in the editor tab and the file explorer (part of https://github.com/eclipsesource/coffee-editor/issues/122).

Add label provider for workflow diagrams

---

client/examples/workflow/workflow-modelserver-theia/src/browser/diagram/workflow-diagram-manager.ts
client/examples/workflow/workflow-modelserver-theia/src/browser/diagram/workflow-glsp-server-options.ts
client/packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts

- Send all available options with the RequestModelAction
- Allow options to be sent to server using 'serverOptions'
- Allow options to be sent as key-value pairs in the uri query string

Provide more flexibility in sending options to the server during open

---

server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/WorkflowModelServerGLSPModule.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/handler/ApplyLabelEditOperationHandler.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/handler/ModelStateAwareOperationHandler.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerAccess.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerModelFactory.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowSubscriptionListener.java

- Provide dedicated operation handler that provides model access
- Adapt label edit to send SET command to model server for task rename
- Execute any command received from model server on local model

Fixes #333: Support SET command for renaming tasks

---

server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerModelFactory.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowSubscriptionListener.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionProcessor.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/di/GLSPModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/DIActionProcessor.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/di/DefaultGLSPModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/jsonrpc/DefaultGLSPServer.java

Resolve #341 
* Rename `ActionDispatcher` to `ActionProcessor`
* Introduce `process` Method that dispatches to the corresponding action handler and sends the response to the client
* Remove redundant code from `DefaultGLSPServer`

Resolves #341 Refactor ActionDispatcher

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowCommandPaletteActionProvider.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/CommandPaletteActionProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestCommandPaletteActionsHandler.java

There isn't really a reason why we don't pass the model state on to the
provider directly instead of only providing it the model root. Providing
the root only, however, makes it less flexible for extenders who also
extend the model state with important per-editor data.

Pass model state to command palette action provider

---

client/packages/sprotty-client/css/glsp-sprotty.css

Sometimes it happens that a text in the SVG diagram gets selected which
leads to an ugly background of the selected text. With this change, we
deactivate the background of selected text in the SVG.

Avoid background of selected text in SVG

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/layout/WorkflowLayoutEngine.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/layout/ILayoutEngine.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/GEdgePlacement.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/GraphPackage.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/impl/GEdgePlacementImpl.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/impl/GraphFactoryImpl.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/impl/GraphPackageImpl.java
server/glsp-graph/src/main/java/com/eclipsesource/glsp/graph/builder/impl/GEdgePlacementBuilder.java
server/glsp-graph/src/main/java/com/eclipsesource/glsp/graph/util/GConstants.java
server/glsp-graph/src/main/resources/glsp-graph.ecore
server/glsp-graph/src/main/resources/glsp-graph.genmodel
server/glsp-layout/src/main/java/com/eclipsesource/glsp/layout/ElkLayoutEngine.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/CollapseExpandActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ComputedBoundsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ExecuteServerCommandActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/LayoutActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ModelSubmissionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OpenActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestCommandPaletteActionsHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestMarkersHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestPopupModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestTypeHintsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SaveModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SelectActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ValidateLabelEditActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/di/DefaultGLSPModule.java

Also: 
+ Pass entire modelState to LayoutEngine instead of just the modelroot
+ Add missing rotate attribute to GEdgePlacement and fix wrong serialization of EdgeSide enum by using String instead
+Set visibility of injected fields of default action handlers to protected (for better extensibility)

Add utility method for rebinding default ActionHandlers

---

server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/ModelServerSubscriptionListener.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/WorkflowModelServerGLSPServerLauncher.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerModelFactory.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerSubscriptionListener.java

- Remove empty ModelServerSubscriptionListener commited by mistake
- Rename WorkflowSubscriptionListener to WorkflowModelServerSubscriptionListener to better fit with the general naming

Ensure Command Package is registered for GLSP workflow model server

---

client/packages/sprotty-client/src/features/tools/change-bounds-tool.ts
client/packages/sprotty-client/src/features/tools/creation-tool.ts
client/packages/sprotty-client/src/features/tools/drag-aware-mouse-listener.ts
client/packages/sprotty-client/src/features/tools/edge-edit-tool.ts

Change visibility of members and methods to protected (if private is not strictly necessary). This enables easier customization of the provided default tools without unnecessary code duplication.

Improve extensibility of tool mouse listeners

---

client/packages/sprotty-client/src/features/tool-feedback/creation-tool-feedback.ts
client/packages/sprotty-client/src/utils/viewpoint-util.ts

Make routerKind of feedback edge configurable
- Add cssClass to enable dedicated feedback edge styling
- Fix issue with the initial location calculation of the feedback edge (Was incorrect for nested element like ports)
- Add utility methods to viewport-utils

Resolve #396 RouterKind for FeedbackEdge
