eclipsesource/graphical-lsp

.travis.yml
client/package.json

Adding client-side build to CI

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowServerRuntimeModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/AbstractActionHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionRegistry.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ActionKind.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/ExecuteServerCommandAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/command/ServerCommandHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/di/GLSPModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/operations/Operation.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/ActionHandlerProvider.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/OperationHandlerProvider.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/ServerCommandHandlerProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerModule.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/CollapseExpandActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ComputedBoundsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OpenActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestOperationsHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestPopupModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SaveModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SelectActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/provider/DefaultActionHandlerProvider.java

This PR is mainly a code Cleanup and Simplification of the glsp server API
* Swapped from multibindings to standard guice bindings for provider classes
* Clean up of deprecated/stale code
In addition, the server API has been prepared for handling ExecuteServerCommandActions as mentioned in https://github.com/eclipsesource/ecore-glsp/issues/6

Refactoring & Cleanup of Server API

---

.travis.yml

Travis now also starts a build on changes on a branch called "ci-configuration-test". This branch can be used to test new ci configurations settings without having the limitations of a  PR environment.

Update travis conifgurations

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/SetOperationsAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/ServerCommandHandlerProvider.java

Fix some incorrectly named methods/parameters

Minor refactoring of server code

---

.travis.yml
scripts/deployMaven.sh
server/pom.xml
server/settings.xml

Improve deployment process for maven and add signing step

Update travis configuration

---

client/packages/workflow-sprotty/css/dark/diagram.css
client/packages/workflow-sprotty/css/light/diagram.css

Fix css styling issue for selected nodes

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/di/GLSPModule.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/jsonrpc/GLSPClient.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/jsonrpc/GLSPClientAware.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/jsonrpc/GLSPServer.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/DefaultGLSPServer.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerLauncher.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/ServerModule.java

Refactor type prefixes on serverside to GLSP (Counterpart PR to #126)

Server code refactoring

---

client/packages/workflow-sprotty/css/dark/popup.css
client/packages/workflow-sprotty/css/light/diagram.css
client/packages/workflow-sprotty/css/light/popup.css
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowPopupFactory.java

Hovering over a model element now requests and correctly displays the corresponding popup from the server.
NOTE: The current popup simply displays the properties of the element and is just a prove of concept implementation which will probably be replaced in the future.

Fix #97 Popups not displayed properly

---

server/example/workflow-example/pom.xml
server/glsp-server/pom.xml

In #155 we forgot to update the version of internal dependencies.

Hotfix for #155

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/UpdateModelAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/model/ModelState.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ModelOptions.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ComputedBoundsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/ModelSubmissionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/OperationActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/ModelStateImpl.java

Improvements for the server API
- Refactor/Cleanup `ModelState` 
- Refactor `UpdateModelAction` to be conform to the sprotty pendant on client side
- Refactor `SubmissionHandler` to enable a separation of layouting concerns
(i.e. micro layout on client side, macro layout on server side)

Fix #153 Revise model requests and layouting

---

client/packages/glsp-theia-extension/src/browser/diagram/glsp-diagram-manager.ts
client/packages/workflow-glsp-extension/src/browser/diagram/workflow-diagram-manager..ts

Fix #164 Restrict diagram editor open handler

Fix #164 Restrict diagram editor open handler

---

client/yarn.lock

Github reports security alerts, so I thought it might be a good
idea to upgrade all dependencies and see if they can be resolved
with an upgrade.

Upgrade yarn dependencies

---

client/packages/glsp-theia-extension/src/browser/language/glsp-client.ts

For some reason this method has been removed in
39220018a28aa204fe30c8cf158f0e46721be057
but this causes the type error reported in #208.
Fixes #208

Re-add BaseGLSPClient.handleConnectionError

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowCommandPaletteActionProvider.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowDiagramManager.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowOperationConfiguration.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/schema/ModelTypes.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/DefaultModelTypes.java

Reusable constants/util class for DefaultModel types

Add util class for default ModelTypes

---

.travis.yml
README.md
scripts/deployNPM.sh

This should fix the failing CI build on master.
In addition, I added a "Build artifacts" section to the readme

Fix failing CI build

---

scripts/deployP2.sh

- Regenerate target before deployment
- Properly configure git user information

Improve deployP2.sh

---

client/examples/workflow/workflow-sprotty/src/di.config.ts
client/packages/sprotty-client/css/glsp-sprotty.css
client/packages/sprotty-client/src/base/di.config.ts
client/packages/sprotty-client/src/base/views/viewer-options.ts
client/packages/sprotty-client/src/features/tool-feedback/change-bounds-tool-feedback.ts
client/packages/sprotty-client/src/features/tool-feedback/cursor-feedback.ts
client/packages/sprotty-client/src/features/tools/change-bounds-tool.ts
client/packages/sprotty-client/src/features/tools/edge-edit-tool.ts
client/packages/sprotty-client/src/index.ts
client/packages/sprotty-client/src/types.ts

Added element collision detection, based on the GLSPViewerOptions by @tortmayr

Element collision detection

---

scripts/deployNPM.sh

Fix issues with npm deployment script.

Fix #261 Automated NPM deployment

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateWeightedEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/ReconnectEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/RerouteEdgeHandler.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/SModelIndex.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/operationhandler/CreateConnectionOperationHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/util/SModelUtil.java

- Add find method to model index for querying model elements matching a predicate
- Add Connectable predicate
- Make result of  createConnection  in CreateConnectionOperationHandler optional

Fix #269 Edge creation for ports does not work

---

.travis.yml
server/example/workflow-example/pom.xml
server/glsp-graph/pom.xml
server/glsp-server-websocket/pom.xml
server/glsp-server/pom.xml
server/pom.xml

Update travis conf to fix build issues

Resolve #288 - Fix missing resources

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/factory/ModelFactory.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/FileBasedModelFactory.java

Add modelState argument to ModelFactory.loadModel()

Resolve #302 

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateActivityNodeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateAutomatedTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateManualTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateMergeNodeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateTaskHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/handler/CreateWeightedEdgeHandler.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/utils/ModelTypes.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/utils/WorkflowBuilder.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/CoffeeTypeUtil.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowFacade.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerModelFactory.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/util/GModelUtil.java

- Provide mapping for coffee example to workflow model elements
- Provide convenience builder for workflow model elements
- Use builder in factory and in creation handlers
Please note this PR depends on https://github.com/eclipsesource/graphical-lsp/pull/307 so the changes look far bigger than what I actually did (for now) ;-)

Provide factory to map from (coffee, notation) to workflow model

---

client/examples/workflow/workflow-modelserver-theia/package.json
client/examples/workflow/workflow-modelserver-theia/src/browser/frontend-module.ts
client/examples/workflow/workflow-modelserver-theia/src/browser/language/workflow-glsp-client-contribution.ts
client/packages/theia-integration/src/browser/language/glsp-client-contribution.ts
client/yarn.lock
server/example/workflow-modelserver-example/pom.xml
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/ModelServerClientProvider.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/ModelServerSubscriptionListener.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/WorkflowModelServerClient.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/WorkflowModelServerGLSPModule.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/WorkflowModelServerGLSPServer.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/WorkflowModelServerGLSPServerLauncher.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/handler/ModelServerAwareOperationActionHandler.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerAccess.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerModelFactory.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowSubscriptionListener.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/model/GraphicalModelState.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/types/ServerStatus.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ClientOptions.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/LayoutUtil.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestOperationsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestTypeHintsActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/SaveModelActionHandler.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/jsonrpc/DefaultGLSPServer.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/DefaultModelStateProvider.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/ModelStateImpl.java

Connects workflow-modelserver-example to actual model server.
- GLSP client starts modelserver from jar
- Handlers for model modification communicate with the model server instead of directly persisting the changes
- GLSP Server subscribes to model server on init and reacts to model updates (Trigger GModel generation and update client)
There is still one known issue with the delete handler. Occasionally the delete operation can cause an exception. Probably related to #315

Modelserver integration

---

server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowModelServerAccess.java
server/example/workflow-modelserver-example/src/main/java/com/eclipsesource/glsp/example/modelserver/workflow/model/WorkflowSubscriptionListener.java

Matching update model server from https://github.com/eclipsesource/modelserver/pull/97

Update to latest model server subscription mechanism

---

client/examples/workflow/workflow-sprotty/src/di.config.ts
client/packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ClientOptions.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestModelActionHandler.java

Resolve #349 Add possibility to disable clientside layouting

Resolve #349 Delegate Vieweroptions.needsClientLayout to server

---

client/examples/workflow/browser-app/package.json
client/examples/workflow/workflow-modelserver-theia/package.json
client/examples/workflow/workflow-modelserver-theia/scripts/download-server.sh
client/examples/workflow/workflow-modelserver-theia/scripts/functions.sh
client/examples/workflow/workflow-modelserver-theia/src/node/backend-module.ts
client/yarn.lock
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/FileBasedModelFactory.java

_Client:_
- Remove dependency to `@modelserver/coffe-theia`
- Extend workflow-modelserver-theia package to launch the modelserver jar
- Add script for downloading latest modelserver jar snapshot
_Server:_
- Fix issue with sourceUri resolution in `FilebasedModelFactory`

Resolve #350 Fix workflow examples

---

client/package.json
client/packages/sprotty-client/css/command-palette.css
client/packages/sprotty-client/package.json
client/packages/sprotty-client/src/features/command-palette/action-definitions.ts
client/packages/sprotty-client/src/features/command-palette/action-provider.ts
client/yarn.lock
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowCommandPaletteActionProvider.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/ActionProcessor.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/CreateNodeOperationAction.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/action/kind/RequestCommandPaletteActions.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/provider/CommandPaletteActionProvider.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/types/LabeledAction.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestCommandPaletteActionsHandler.java

Support new command palette context info and enhancements in Sprotty

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/utils/WorkflowBuilder.java
server/example/workflow-example/src/test/java/com/eclipsesource/glsp/example/workflow/test/ReadAndWriteWorkflowGraphJsonTest.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/GEdge.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/GraphPackage.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/impl/GEdgeImpl.java
server/glsp-graph/src/main/java-gen/com/eclipsesource/glsp/graph/impl/GraphPackageImpl.java
server/glsp-graph/src/main/java/com/eclipsesource/glsp/graph/builder/AbstractGEdgeBuilder.java
server/glsp-graph/src/main/java/com/eclipsesource/glsp/graph/util/GConstants.java
server/glsp-graph/src/main/resources/glsp-graph.ecore
server/glsp-graph/src/main/resources/glsp-graph.genmodel

Also: Add missing "routerKind" property to GEdge.  (Client evaluates this property and applies the corresponding routing style)

Resolve #362 Constants for string property values

---

client/packages/theia-integration/src/browser/diagram/glsp-theia-sprotty-connector.ts
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/jsonrpc/GLSPServerException.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ServerStatusUtil.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/model/ModelStateImpl.java

* Add utility methods to GLSPServerException
* Expose commandStack of ModelStateImpl to subclasses

Add utility methods to GLSPServerException (#370)

---

server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowPopupFactory.java
server/glsp-api/src/main/java/com/eclipsesource/glsp/api/factory/PopupModelFactory.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/actionhandler/RequestPopupModelActionHandler.java

- Hand modelState to PopupModelFactory
- Fix type on method
- Use Optional instead of 'allowing' null values

Make PopupModelFactory more flexible by providing modelstate

---

server/glsp-api/src/main/java/com/eclipsesource/glsp/api/utils/ServerStatusUtil.java
server/glsp-server/src/main/java/com/eclipsesource/glsp/server/jsonrpc/DefaultGLSPServer.java

Ensure that the complete exception stack trace is logged and also reported back to the client.

Improve exception handling

---

client/packages/sprotty-client/src/features/tools/creation-tool.ts
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorfklowDiagramConfiguration.java
server/example/workflow-example/src/main/java/com/eclipsesource/glsp/example/workflow/WorkflowGLSPModule.java

Fix edge hint interpretation on the server

---

client/package.json
client/packages/theia-integration/package.json
client/yarn.lock

Update to latest sprotty-theia version to consume this PR: https://github.com/eclipse/sprotty-theia/pull/44

Update sprotty-theia dependency

---

server/example/workflow-example/pom.xml
server/example/workflow-modelserver-example/pom.xml
server/glsp-api/pom.xml
server/glsp-layout/pom.xml
server/glsp-server-websocket/pom.xml
server/glsp-server/pom.xml

In addition, change elk dependencies to stable version and remove redundant dependency definitions

Update lsp4j dependencies
